# Generated by Django 4.2.29 on 2026-04-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userneocredentials',
            name='consumer_secret',
        ),
        migrations.RemoveField(
            model_name='userneocredentials',
            name='totp_secret',
        ),
        migrations.AddField(
            model_name='userneocredentials',
            name='sdk_session_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userneocredentials',
            name='sdk_session_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userneocredentials',
            name='sdk_session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userneocredentials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
