# Generated by Django 4.2.29 on 2026-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_smtpsettings_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsettings',
            name='enable_registration_otp',
            field=models.BooleanField(default=False),
        ),
    ]
