# Generated by Django 4.2.29 on 2026-04-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='enable_user_registration',
            field=models.BooleanField(default=True, help_text='Allow new users to register via the signup button'),
        ),
    ]
