# Generated by Django 6.0.7 on 2026-07-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0011_platformsettings_allow_session_restore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtpsettings",
            name="enable_order_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
