# Generated by Django 6.0.7 on 2026-07-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0012_smtpsettings_enable_order_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtpsettings",
            name="forgot_password_subject",
            field=models.CharField(
                default="JK Terminal - Temporary Password", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="smtpsettings",
            name="forgot_password_template",
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f5f7; margin: 0; padding: 0; color: #1e293b; }\n    .container { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }\n    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 32px 24px; text-align: center; }\n    .header h1 { margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }\n    .content { padding: 32px 24px; line-height: 1.6; }\n    .footer { text-align: center; padding: 24px; font-size: 12px; color: #64748b; background-color: #f8fafc; border-top: 1px solid #f1f5f9; }\n    .highlight-box { background-color: #f1f5f9; border-left: 4px solid #667eea; padding: 16px; border-radius: 0 8px 8px 0; font-family: monospace; font-size: 20px; text-align: center; margin: 24px 0; color: #0f172a; font-weight: bold; }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>JK Terminal</h1>\n    </div>\n    <div class="content">\n      <p>Hello <strong>{{ username }}</strong>,</p>\n      <p>Your temporary password is:</p>\n      <div class="highlight-box">{{ temp_password }}</div>\n      <p>Please login using this temporary password. You will be prompted to set a new permanent password immediately upon logging in.</p>\n      <p>Thank you,<br>JK Terminal Team</p>\n    </div>\n    <div class="footer">\n      This is an automated notification from JK Terminal. Please do not reply to this email.\n    </div>\n  </div>\n</body>\n</html>'
            ),
        ),
        migrations.AddField(
            model_name="smtpsettings",
            name="from_name",
            field=models.CharField(
                blank=True, default="JK Terminal", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="smtpsettings",
            name="order_placed_subject",
            field=models.CharField(
                default="JK Terminal - Trade Order Placed: {{ trading_symbol }}",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="smtpsettings",
            name="order_placed_template",
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f5f7; margin: 0; padding: 0; color: #1e293b; }\n    .container { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }\n    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 32px 24px; text-align: center; }\n    .header h1 { margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }\n    .content { padding: 32px 24px; line-height: 1.6; }\n    .footer { text-align: center; padding: 24px; font-size: 12px; color: #64748b; background-color: #f8fafc; border-top: 1px solid #f1f5f9; }\n    .details-list { width: 100%; border-collapse: collapse; margin: 24px 0; }\n    .details-list td { padding: 12px; border-bottom: 1px solid #e2e8f0; }\n    .details-list td.label { font-weight: 600; color: #475569; width: 40%; }\n    .details-list td.value { color: #0f172a; }\n    .badge-buy { display: inline-block; padding: 2px 8px; background-color: #dcfce7; color: #15803d; border-radius: 4px; font-weight: 600; font-size: 12px; }\n    .badge-sell { display: inline-block; padding: 2px 8px; background-color: #fee2e2; color: #b91c1c; border-radius: 4px; font-weight: 600; font-size: 12px; }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>JK Terminal</h1>\n    </div>\n    <div class="content">\n      <p>Hello <strong>{{ username }}</strong>,</p>\n      <p>A new trade order has been successfully placed on your account:</p>\n      \n      <table class="details-list">\n        <tr>\n          <td class="label">Instrument</td>\n          <td class="value"><strong>{{ trading_symbol }}</strong></td>\n        </tr>\n        <tr>\n          <td class="label">Transaction Type</td>\n          <td class="value">\n            {% if transaction_type == "B" %}\n              <span class="badge-buy">BUY</span>\n            {% else %}\n              <span class="badge-sell">SELL</span>\n            {% endif %}\n          </td>\n        </tr>\n        <tr>\n          <td class="label">Quantity</td>\n          <td class="value">{{ quantity }}</td>\n        </tr>\n        <tr>\n          <td class="label">Price</td>\n          <td class="value">{% if order_type != "MKT" %}{{ price }}{% else %}Market{% endif %}</td>\n        </tr>\n        <tr>\n          <td class="label">Order Type</td>\n          <td class="value">{{ order_type }}</td>\n        </tr>\n        <tr>\n          <td class="label">Product</td>\n          <td class="value">{{ product_type }}</td>\n        </tr>\n        <tr>\n          <td class="label">Exchange</td>\n          <td class="value">{{ exchange_segment }}</td>\n        </tr>\n        <tr>\n          <td class="label">Order ID</td>\n          <td class="value"><code>{{ order_id }}</code></td>\n        </tr>\n      </table>\n      \n      <p>Regards,<br>JK Terminal</p>\n    </div>\n    <div class="footer">\n      This is an automated notification from JK Terminal. Please do not reply to this email.\n    </div>\n  </div>\n</body>\n</html>'
            ),
        ),
        migrations.AddField(
            model_name="smtpsettings",
            name="otp_subject",
            field=models.CharField(
                default="JK Terminal - Registration Verification", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="smtpsettings",
            name="otp_template",
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f5f7; margin: 0; padding: 0; color: #1e293b; }\n    .container { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }\n    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 32px 24px; text-align: center; }\n    .header h1 { margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }\n    .content { padding: 32px 24px; line-height: 1.6; }\n    .footer { text-align: center; padding: 24px; font-size: 12px; color: #64748b; background-color: #f8fafc; border-top: 1px solid #f1f5f9; }\n    .highlight-box { background-color: #f1f5f9; border-left: 4px solid #667eea; padding: 16px; border-radius: 0 8px 8px 0; font-family: monospace; font-size: 24px; letter-spacing: 4px; text-align: center; margin: 24px 0; color: #0f172a; font-weight: bold; }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>JK Terminal</h1>\n    </div>\n    <div class="content">\n      <p>Hello <strong>{{ username }}</strong>,</p>\n      <p>Your account verification code is:</p>\n      <div class="highlight-box">{{ otp }}</div>\n      <p>Please enter this code to complete your registration. If you did not request this code, you can safely ignore this email.</p>\n      <p>Thank you,<br>JK Terminal Team</p>\n    </div>\n    <div class="footer">\n      This is an automated notification from JK Terminal. Please do not reply to this email.\n    </div>\n  </div>\n</body>\n</html>'
            ),
        ),
        migrations.AddField(
            model_name="smtpsettings",
            name="password_changed_subject",
            field=models.CharField(
                default="JK Terminal - Password Changed Successfully", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="smtpsettings",
            name="password_changed_template",
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f5f7; margin: 0; padding: 0; color: #1e293b; }\n    .container { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }\n    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 32px 24px; text-align: center; }\n    .header h1 { margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }\n    .content { padding: 32px 24px; line-height: 1.6; }\n    .footer { text-align: center; padding: 24px; font-size: 12px; color: #64748b; background-color: #f8fafc; border-top: 1px solid #f1f5f9; }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>JK Terminal</h1>\n    </div>\n    <div class="content">\n      <p>Hello <strong>{{ username }}</strong>,</p>\n      <p>Your password has been successfully changed.</p>\n      <p>If you did not authorize this change, please contact an administrator immediately to secure your account.</p>\n      <p>Thank you,<br>JK Terminal Team</p>\n    </div>\n    <div class="footer">\n      This is an automated notification from JK Terminal. Please do not reply to this email.\n    </div>\n  </div>\n</body>\n</html>'
            ),
        ),
    ]
