# Generated by Django 6.0.7 on 2026-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0013_smtpsettings_forgot_password_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userneocredentials",
            name="auth_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Auth using Auth Code"),
                    ("secret", "Direct Auth using Secret"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userneocredentials",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
