# Generated by Django 6.0.7 on 2026-07-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0014_userneocredentials_auth_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="allow_direct_secret_auth",
            field=models.BooleanField(
                default=True,
                help_text="Allow users to use a TOTP secret for direct session activation",
            ),
        ),
    ]
