# Generated by Django 6.0.7 on 2026-08-02 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0015_platformsettings_allow_direct_secret_auth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="smtpsettings",
            name="order_status_subject",
            field=models.CharField(
                default="JK Terminal - Order {{ order_id }} Status Update: {{ last_status }}",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="smtpsettings",
            name="order_status_template",
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f5f7; margin: 0; padding: 0; color: #1e293b; }\n    .container { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }\n    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 32px 24px; text-align: center; }\n    .header h1 { margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }\n    .content { padding: 32px 24px; line-height: 1.6; }\n    .footer { text-align: center; padding: 24px; font-size: 12px; color: #64748b; background-color: #f8fafc; border-top: 1px solid #f1f5f9; }\n    .details-list { width: 100%; border-collapse: collapse; margin: 24px 0; }\n    .details-list td { padding: 12px; border-bottom: 1px solid #e2e8f0; }\n    .details-list td.label { font-weight: 600; color: #475569; width: 40%; }\n    .details-list td.value { color: #0f172a; }\n    .status-badge { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-weight: 700; font-size: 14px; text-transform: uppercase; }\n    .status-complete { background-color: #dcfce7; color: #15803d; }\n    .status-open { background-color: #dbeafe; color: #1d4ed8; }\n    .status-rejected { background-color: #fee2e2; color: #b91c1c; }\n    .status-cancelled { background-color: #f3f4f6; color: #374151; }\n    .status-other { background-color: #fef9c3; color: #a16207; }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>JK Terminal</h1>\n    </div>\n    <div class="content">\n      <p>Hello <strong>{{ username }}</strong>,</p>\n      <p>Your order status has updated:</p>\n      \n      <div style="text-align: center; margin: 24px 0;">\n        <span class="status-badge {% if last_status == \'complete\' %}status-complete{% elif last_status == \'open\' %}status-open{% elif last_status == \'rejected\' %}status-rejected{% elif last_status == \'cancelled\' %}status-cancelled{% else %}status-other{% endif %}">\n          {{ last_status }}\n        </span>\n      </div>\n\n      <table class="details-list">\n        <tr>\n          <td class="label">Instrument</td>\n          <td class="value"><strong>{{ trading_symbol }}</strong></td>\n        </tr>\n        <tr>\n          <td class="label">Transaction Type</td>\n          <td class="value">{{ transaction_type }}</td>\n        </tr>\n        <tr>\n          <td class="label">Quantity</td>\n          <td class="value">{{ quantity }}</td>\n        </tr>\n        <tr>\n          <td class="label">Price</td>\n          <td class="value">₹{{ price }}</td>\n        </tr>\n        <tr>\n          <td class="label">Order ID</td>\n          <td class="value"><code>{{ order_id }}</code></td>\n        </tr>\n      </table>\n      \n      <p>Regards,<br>JK Terminal</p>\n    </div>\n    <div class="footer">\n      This is an automated notification from JK Terminal. Please do not reply to this email.\n    </div>\n  </div>\n</body>\n</html>'
            ),
        ),
        migrations.CreateModel(
            name="TrackedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, unique=True)),
                ("trading_symbol", models.CharField(max_length=255)),
                ("transaction_type", models.CharField(max_length=10)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
                ("order_type", models.CharField(max_length=10)),
                ("product_type", models.CharField(max_length=20)),
                ("exchange_segment", models.CharField(max_length=20)),
                ("last_status", models.CharField(max_length=50)),
                ("is_terminal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracked Order",
                "verbose_name_plural": "Tracked Orders",
            },
        ),
    ]
