# Generated by Django 6.0.7 on 2026-08-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0016_smtpsettings_order_status_subject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveMarketData",
            fields=[
                (
                    "symbol",
                    models.CharField(
                        blank=True, db_column="pSymbol", max_length=100, null=True
                    ),
                ),
                (
                    "exch_seg",
                    models.CharField(
                        blank=True, db_column="pExchSeg", max_length=50, null=True
                    ),
                ),
                (
                    "symbol_name",
                    models.CharField(
                        blank=True, db_column="pSymbolName", max_length=255, null=True
                    ),
                ),
                (
                    "trd_symbol",
                    models.CharField(
                        blank=True, db_column="pTrdSymbol", max_length=255, null=True
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        blank=True, db_column="pOptionType", max_length=20, null=True
                    ),
                ),
                (
                    "inst_type",
                    models.CharField(
                        blank=True, db_column="pInstType", max_length=50, null=True
                    ),
                ),
                (
                    "strike_price",
                    models.FloatField(blank=True, db_column="dStrikePrice", null=True),
                ),
                (
                    "scrip_ref_key",
                    models.CharField(
                        db_column="pScripRefKey",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("desc", models.TextField(blank=True, db_column="pDesc", null=True)),
                (
                    "group",
                    models.CharField(
                        blank=True, db_column="pGroup", max_length=50, null=True
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(
                        blank=True, db_column="pAssetCode", max_length=100, null=True
                    ),
                ),
                (
                    "tick_size",
                    models.FloatField(blank=True, db_column="dTickSize", null=True),
                ),
                (
                    "lot_size",
                    models.IntegerField(blank=True, db_column="lLotSize", null=True),
                ),
                ("expire_date", models.CharField(blank=True, max_length=50, null=True)),
                ("has_option_chain", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "active_market_data",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="smtpsettings",
            name="order_placed_subject",
            field=models.CharField(
                default="JK Terminal - Trade Order Placed: {{ transaction_type }} {{ quantity }} {{ trading_symbol }}",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="smtpsettings",
            name="order_placed_template",
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f5f7; margin: 0; padding: 0; color: #1e293b; }\n    .container { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }\n    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 32px 24px; text-align: center; }\n    .header h1 { margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }\n    .content { padding: 32px 24px; line-height: 1.6; }\n    .footer { text-align: center; padding: 24px; font-size: 12px; color: #64748b; background-color: #f8fafc; border-top: 1px solid #f1f5f9; }\n    .details-list { width: 100%; border-collapse: collapse; margin: 24px 0; }\n    .details-list td { padding: 12px; border-bottom: 1px solid #e2e8f0; }\n    .details-list td.label { font-weight: 600; color: #475569; width: 40%; }\n    .details-list td.value { color: #0f172a; }\n    .badge-buy { display: inline-block; padding: 2px 8px; background-color: #dcfce7; color: #15803d; border-radius: 4px; font-weight: 600; font-size: 12px; }\n    .badge-sell { display: inline-block; padding: 2px 8px; background-color: #fee2e2; color: #b91c1c; border-radius: 4px; font-weight: 600; font-size: 12px; }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>JK Terminal</h1>\n    </div>\n    <div class="content">\n      <p>Hello <strong>{{ username }}</strong>,</p>\n      <p>A new trade order has been successfully placed on your account:</p>\n      \n      <table class="details-list">\n        <tr>\n          <td class="label">Instrument</td>\n          <td class="value"><strong>{{ trading_symbol }}</strong></td>\n        </tr>\n        <tr>\n          <td class="label">Transaction Type</td>\n          <td class="value">\n            {% if transaction_type == "B" or transaction_type == "BUY" %}\n              <span class="badge-buy">BUY</span>\n            {% else %}\n              <span class="badge-sell">SELL</span>\n            {% endif %}\n          </td>\n        </tr>\n        <tr>\n          <td class="label">Quantity</td>\n          <td class="value">{{ quantity }}</td>\n        </tr>\n        <tr>\n          <td class="label">Price</td>\n          <td class="value">{% if order_type != "MKT" %}{{ price }}{% else %}Market{% endif %}</td>\n        </tr>\n        <tr>\n          <td class="label">Order Type</td>\n          <td class="value">{{ order_type }}</td>\n        </tr>\n        <tr>\n          <td class="label">Product</td>\n          <td class="value">{{ product_type }}</td>\n        </tr>\n        <tr>\n          <td class="label">Exchange</td>\n          <td class="value">{{ exchange_segment }}</td>\n        </tr>\n        <tr>\n          <td class="label">Order ID</td>\n          <td class="value"><code>{{ order_id }}</code></td>\n        </tr>\n      </table>\n      \n      <p>Regards,<br>JK Terminal</p>\n    </div>\n    <div class="footer">\n      This is an automated notification from JK Terminal. Please do not reply to this email.\n    </div>\n  </div>\n</body>\n</html>'
            ),
        ),
        migrations.AlterField(
            model_name="smtpsettings",
            name="order_status_subject",
            field=models.CharField(
                default="JK Terminal - Trade Order: {{ transaction_type }} {{ quantity }} {{ trading_symbol }} is {{ last_status }}",
                max_length=255,
            ),
        ),
    ]
