# Generated by Django 6.0.7 on 2026-08-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0017_activemarketdata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtpsettings",
            name="order_modified_subject",
            field=models.CharField(
                default="JK Terminal - Trade Order Modified: {{ transaction_type }} {{ quantity }} {{ trading_symbol }}",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="smtpsettings",
            name="order_modified_template",
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f5f7; margin: 0; padding: 0; color: #1e293b; }\n    .container { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }\n    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 32px 24px; text-align: center; }\n    .header h1 { margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }\n    .content { padding: 32px 24px; line-height: 1.6; }\n    .footer { text-align: center; padding: 24px; font-size: 12px; color: #64748b; background-color: #f8fafc; border-top: 1px solid #f1f5f9; }\n    .details-list { width: 100%; border-collapse: collapse; margin: 24px 0; }\n    .details-list td { padding: 12px; border-bottom: 1px solid #e2e8f0; }\n    .details-list td.label { font-weight: 600; color: #475569; width: 40%; }\n    .details-list td.value { color: #0f172a; }\n    .badge-modify { display: inline-block; padding: 2px 8px; background-color: #dbeafe; color: #1d4ed8; border-radius: 4px; font-weight: 600; font-size: 12px; }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>JK Terminal</h1>\n    </div>\n    <div class="content">\n      <p>Hello <strong>{{ username }}</strong>,</p>\n      <p>Your trade order has been successfully <strong>MODIFIED</strong> with new parameters:</p>\n      \n      <table class="details-list">\n        <tr>\n          <td class="label">Instrument</td>\n          <td class="value"><strong>{{ trading_symbol }}</strong></td>\n        </tr>\n        <tr>\n          <td class="label">Transaction Type</td>\n          <td class="value">\n            <span class="badge-modify">{{ transaction_type }}</span>\n          </td>\n        </tr>\n        <tr>\n          <td class="label">New Quantity</td>\n          <td class="value">{{ quantity }}</td>\n        </tr>\n        <tr>\n          <td class="label">New Price</td>\n          <td class="value">₹{{ price }}</td>\n        </tr>\n        <tr>\n          <td class="label">Order Type</td>\n          <td class="value">{{ order_type }}</td>\n        </tr>\n        <tr>\n          <td class="label">Product</td>\n          <td class="value">{{ product_type }}</td>\n        </tr>\n        <tr>\n          <td class="label">Exchange</td>\n          <td class="value">{{ exchange_segment }}</td>\n        </tr>\n        <tr>\n          <td class="label">Order ID</td>\n          <td class="value"><code>{{ order_id }}</code></td>\n        </tr>\n      </table>\n      \n      <p>Regards,<br>JK Terminal</p>\n    </div>\n    <div class="footer">\n      This is an automated notification from JK Terminal. Please do not reply to this email.\n    </div>\n  </div>\n</body>\n</html>'
            ),
        ),
    ]
